

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: applicationpermissions.sys.bytetrade.io
spec:
  group: sys.bytetrade.io
  names:
    categories:
    - all
    kind: ApplicationPermission
    listKind: ApplicationPermissionList
    plural: applicationpermissions
    shortNames:
    - appperm
    singular: applicationpermission
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.app
      name: the content request app
      type: string
    - jsonPath: .spec.appid
      name: the content request app id
      type: string
    - jsonPath: .spec.key
      name: the content request app key
      type: string
    - jsonPath: .status.state
      name: state
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ApplicationPermission is the Schema for the system server permission control
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ApplicationPermissionSpec defines the desired state of ApplicationPermission
            properties:
              description:
                description: description from ApplicationPermission's description or frontend
                type: string
              app:
                description: the app name of permission require
                type: string
              appid:
                description: the app id of permission require
                type: string
              key:
                description: the app key of application
                type: string
              secret:
                description: the app secret of application
                type: string
              permissions:
                description: the data permission of application
                type: array
                items:
                  type: object
                  properties:
                    dataType:
                      description: the content data type of the provider
                      type: string
                    group:
                      description: The group of the provider
                      type: string
                    version:
                      description: the version of content data type 
                      type: string
                    ops:
                      description: the content data operation permissions
                      type: array
                      items:
                        type: string
            required:
            - app
            - key
            type: object
          status:
            description: ApplicationPermissionStatus defines the observed state of ApplicationPermission
            properties:
              state:
                description: 'the state of the ApplicationPermission: draft, submitted, passed,
                  rejected, suspended, active'
                default: active
                type: string
              statusTime:
                format: date-time
                type: string
              updateTime:
                format: date-time
                type: string
            required:
            - state
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
